In [1]:
from sklearn import datasets
digits=datasets.load_digits()
print(digits.data[0])

[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.   5.
   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.   0.   8.
   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.  11.   0.   1.
  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.   0.   0.   6.  13.
  10.   0.   0.   0.]


In [2]:
print(digits.target[0])

0


In [3]:
print(digits.data[0].shape)

(64,)


In [5]:
print(digits.images[0].shape)

(8, 8)


In [8]:
from sklearn import svm
clf= svm.SVC(gamma=0.001,C=100)

In [9]:
clf.fit(digits.data[:-1],digits.target[:-1])

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
clf.predict(digits.data[-1:])

array([8])

**类型转换**

In [24]:
import numpy as np
from sklearn import random_projection
rng = np.random.RandomState(0)
X = rng.rand(10, 2000)
X = np.array(X, dtype='float32')
print(X.dtype)
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
print(X_new.dtype) 

float32
float64


In [25]:
from sklearn import datasets
from sklearn.svm import SVC
iris = datasets.load_iris()
clf =SVC()
clf.fit(iris.data,iris.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [28]:
clf.fit(iris.data,iris.target_names[iris.target])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

In [31]:
import numpy as np
from sklearn.svm import SVC
rng = np.random.RandomState(0)
X = rng.rand(100, 10)
print(X)
y = rng.binomial(1, 0.5, 100)
print(y)
X_test = rng.rand(5, 10)
print(X_test)

[[  5.48813504e-01   7.15189366e-01   6.02763376e-01   5.44883183e-01
    4.23654799e-01   6.45894113e-01   4.37587211e-01   8.91773001e-01
    9.63662761e-01   3.83441519e-01]
 [  7.91725038e-01   5.28894920e-01   5.68044561e-01   9.25596638e-01
    7.10360582e-02   8.71292997e-02   2.02183974e-02   8.32619846e-01
    7.78156751e-01   8.70012148e-01]
 [  9.78618342e-01   7.99158564e-01   4.61479362e-01   7.80529176e-01
    1.18274426e-01   6.39921021e-01   1.43353287e-01   9.44668917e-01
    5.21848322e-01   4.14661940e-01]
 [  2.64555612e-01   7.74233689e-01   4.56150332e-01   5.68433949e-01
    1.87898004e-02   6.17635497e-01   6.12095723e-01   6.16933997e-01
    9.43748079e-01   6.81820299e-01]
 [  3.59507901e-01   4.37031954e-01   6.97631196e-01   6.02254716e-02
    6.66766715e-01   6.70637870e-01   2.10382561e-01   1.28926298e-01
    3.15428351e-01   3.63710771e-01]
 [  5.70196770e-01   4.38601513e-01   9.88373838e-01   1.02044811e-01
    2.08876756e-01   1.61309518e-01   6.53108

In [32]:
clf=SVC()
clf.set_params(kernel='linear').fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [33]:
clf.predict(X_test)

array([1, 0, 1, 1, 0])

在这里，默认内核rbf首先被改变到linear估计器被构造之后SVC()，并且改回到rbf重新设计估计器并进行第二预测。

**多类与多标签拟合**

In [34]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [35]:
y = LabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

**线性回归**

In [5]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit([[0,0],[1,1],[2,2]],[0,1,2])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [6]:
reg.coef_

array([ 0.5,  0.5])

LinearRegression ( 线性回归 ) 将采用其拟合方法数组 X ， y 并将其线性模型的系数 w 存储在其 coef_ 成员中

**岭回归 Ridge Regression**
岭回归通过对系数的大小施加惩罚项来解决普通话最小二乘的一些问题，ridge coefficients ( 岭系数 ) 最小化了惩罚的残差平方和。

In [8]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=0.5)
reg.fit([[0,0],[1,1],[2,2]],[0,1,2])

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [9]:
reg.coef_

array([ 0.44444444,  0.44444444])

In [10]:
reg.intercept_

0.11111111111111116

reg.coef_：系数w

reg.intercept_:截距

**岭回归设置正则化参数：通过广义交叉验证**

RidgeCV通过设置Alpha参数设置交叉验证来实现岭回归，该对象的工作方式和GridSearchCV相同，只是它默认为 Generalized Cross-Validation ( 通用交叉验证 ) （GCV），这是一种有效的一对一交叉验证形式。

In [13]:
from sklearn import linear_model
reg = linear_model.RidgeCV(alphas=[0.1,1.0,10.0])
reg.fit([[0,0],[1,1],[2,2]],[0,0.1,1])

RidgeCV(alphas=[0.1, 1.0, 10.0], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [14]:
reg.alpha_

1.0

**Lasso**

Lasso是估计稀疏系数的线性模型，它在一些情况下是有用的，因为他倾向于使用较少参数值的解决方案，有效地减少给定解决方案所依赖的变量的数量。为此，Lasso及其变体是compressed sensing（压缩感测领域）的基础，在某些条件下，它可以恢复精确的非零权重集。

In [16]:
from sklearn import linear_model
reg = linear_model.Lasso(alpha=0.1)
reg.fit([[0,0],[1,1]],[0,1])

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [17]:
reg.predict([[1,1]])

array([ 0.8])

**贝叶斯岭回归**

In [41]:
from sklearn import linear_model
x=[[0,0],[1,1],[2,2],[3,3]]
y= [0,1,2,3]
reg = linear_model.BayesianRidge()
reg.fit(x,y)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

In [43]:
reg.predict([[0,1]])

array([ 0.50000013])

In [47]:
reg.coef_

array([ 0.49999993,  0.49999993])

**逻辑回归（Logistic regression）**

尽管它的名字是回归，却是用于分类的线性模型而不是回归，

In [48]:
import numpy as np
x=np.array([1,2,1,2,0,0,])

y=np.array([1,1,1,2,0,0,])
print(np.mean(x==y))


0.833333333333


In [54]:
import numpy as np
XX,YY=np.mgrid[0:5,0:6]

print(XX,YY)

[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]] [[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [65]:
print(XX.ravel())
print(YY.ravel())
Z= np.c_[XX.ravel(), YY.ravel()]
print(Z)
print(Z.shape)

[0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4]
[0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5]
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]]
(30, 2)


In [73]:
XX

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4]])

In [74]:
XX[[2,3]]

array([[2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3]])